language: ruby
rvm:
  - 2.3.1

# Use Postgres 9.5
# https://www.brandur.org/fragments/postgres-95-travis
dist: trusty
sudo: required
addons:
  postgresql: "9.5"

before_install:
  - gem update bundler
  - psql -c 'create database recipes_test;' -U postgres
script: bundle exec rake test

# To stop Travis from running tests for a new commit,
# add the following to your commit message: [ci skip]
# You should add this when you edit documentation or comments, etc.
